function myResponsiveGUI
    % Create main figure window
    fig = figure('Name', 'Real-Time Monitoring GUI', ...
                 'Units', 'normalized', ...
                 'Position', [0.1, 0.075, 0.8, 0.8]); % Placeholder: Adjust as needed
    
    % Control Panel
    controlPanel = uipanel('Parent', fig, 'Title', 'Controls', ...
                           'Units', 'normalized', 'Position', [0.066, 0.873, 0.425, 0.1]);
    
    % Dropdown menu (Select Device)
    dropdown_device = uicontrol('Parent', controlPanel, 'Style', 'popupmenu', ...
                         'String', {'Select Device', 'Device 1', 'Device 2'}, ...
                         'Units', 'normalized', ...
                         'Position', [0.05, 0.55, 0.28, 0.35]); % Adjusted for control panel
    
    % Dropdown menu (Input Shaft Rate)
    dropdown_shaftrate = uicontrol('Parent', controlPanel, 'Style', 'popupmenu', ...
                         'String', {'Shaft Rate', 'Device 1', 'Device 2'}, ...
                         'Units', 'normalized', ...
                         'Position', [0.35, 0.55, 0.28, 0.35]); 

    % Dropdown menu (Sample Frequency)
    dropdown_samplefreq = uicontrol('Parent', controlPanel, 'Style', 'popupmenu', ...
                         'String', {'Sample Frequency', 'Device 1', 'Device 2'}, ...
                         'Units', 'normalized', ...
                         'Position', [0.65, 0.55, 0.28, 0.35]); 

    % Buttons inside control panel
    startButton = uicontrol('Parent', controlPanel, 'Style', 'pushbutton', ...
                            'String', 'Start Real-Time Plot', ...
                            'Units', 'normalized', ...
                            'Position', [0.05, 0.1, 0.28, 0.35]); 
    
    recordButton = uicontrol('Parent', controlPanel, 'Style', 'pushbutton', ...
                             'String', 'Record Data', ...
                             'Units', 'normalized', ...
                             'Position', [0.35, 0.1, 0.28, 0.35]); 
    
    classifyButton = uicontrol('Parent', controlPanel, 'Style', 'pushbutton', ...
                               'String', 'Classify', ...
                               'Units', 'normalized', ...
                               'Position', [0.65, 0.1, 0.28, 0.35]); 

    % Panels for figures
    panel1 = uipanel('Parent', fig, 'Title', 'Real-Time Time Domain Feed', ...
                     'Units', 'normalized', 'Position', [0.066, 0.443, 0.425, 0.4]); 
    ax1 = axes('Parent', panel1, 'Units', 'normalized', 'Position', [0.15, 0.2, 0.75, 0.7]);
    xlabel(ax1, 'Time (s)');
    ylabel(ax1, 'Amplitude');

    panel2 = uipanel('Parent', fig, 'Title', 'Real-Time FFT', ...
                     'Units', 'normalized', 'Position', [0.066, 0.025, 0.425, 0.4]); 
    ax2 = axes('Parent', panel2, 'Units', 'normalized', 'Position', [0.15, 0.2, 0.75, 0.7]);
    xlabel(ax2, 'Frequency (Hz)');
    ylabel(ax2, 'Magnitude');

    panel3 = uipanel('Parent', fig, 'Title', 'Fault Indicator 1', ...
                     'Units', 'normalized', 'Position', [0.525, 0.443, 0.425, 0.4]); 
    ax3 = axes('Parent', panel3, 'Units', 'normalized', 'Position', [0.15, 0.2, 0.75, 0.7]);
    xlabel(ax3, 'Time (s)');
    ylabel(ax3, 'Fault Metric');

    panel4 = uipanel('Parent', fig, 'Title', 'Fault Indicator 2', ...
                     'Units', 'normalized', 'Position', [0.525, 0.025, 0.425, 0.4]); 
    ax4 = axes('Parent', panel4, 'Units', 'normalized', 'Position', [0.15, 0.2, 0.75, 0.7]);
    xlabel(ax4, 'Time (s)');
    ylabel(ax4, 'Fault Metric');

    % Panel for the Grid Display
    gridPanel = uipanel('Parent', fig, 'Title', 'Fault Classification', ...
                        'Units', 'normalized', 'Position', [0.525, 0.873, 0.425, 0.1]); 
    
    % Column Headers
    columnNames = {'Baseline', 'Imbalance', 'Angular M.', ...
                   'Parallel M.', 'Debris', 'Lubricant'};

    % Example Data (Replace with actual values)
    rowData = [10, 20, 30, 15, 5, 20];  % Example percentage values

    % Create Header Labels
    for i = 1:6
        uicontrol('Parent', gridPanel, 'Style', 'text', ...
                  'String', columnNames{i}, ...
                  'Units', 'normalized', ...
                  'Position', [(i-1)/6, 0.55, 1/6, 0.4], ...
                  'FontSize', 10, 'FontWeight', 'bold');
    end

    % Create Value Labels
    for i = 1:6
        uicontrol('Parent', gridPanel, 'Style', 'text', ...
                  'String', sprintf('%.1f%%', rowData(i)), ...
                  'Units', 'normalized', ...
                  'Position', [(i-1)/6, 0.1, 1/6, 0.4], ...
                  'FontSize', 10);
    end
end
